### PR TITLE
Update jekyll-commonmark-ghpages.rb

### PR DESCRIPTION
**Pull request by lpugin**
Close the `<br>` tag for use in xhtml pages

### CODE REVIEW

**Comment by lpugin** [comment]
This should hopefully fix issue #3

**Comment by kivikakk** [comment]
I suspect you misunderstand the code here; it adds the `<br>`s only to remove them after remove them when done. The code change as you've made it is also a syntax error — note the unescaped forward slash in `/<br data-jekyll-commonmark-ghpages />/`.

Would you mind adding a test that demonstrates the outcome you're trying to achieve?

**Comment by kivikakk** [comment]
> I am not sure I understand this. Why adding them then?

It's done in order to preserve the newlines correctly across the syntax highlighting process.

> What I am trying to achieve is for it to work as before. I did not change anything on my side, but it seems that the `<br>` are now added. It is something new that is not generated with kramdown (locally) but that breaks the generated xhtml when generated on the github server.

Without a test case it's hard to know exactly what you're referring to here, but do try and we'll see if we can get something working.

**Comment by lpugin** [comment]
This now works with xhtml pages by adding valid xml `<br>`.

**Comment by kivikakk** [comment]
Have you tested this change? It simply won't do what you want it to. The `<br>`s are being added elsewhere; possibly in the highlighter itself (`rouge`), or by `commonmarker`.

**Comment by kivikakk** [comment]
We are changing `\n` to `<br data-jekyll-commonmark-ghpages>` so we can preserve newlines without them being mangled by `commonmarker`. After rendering the CommonMark (with highlighted syntax embedded as HTML) to HTML, we return those to `\n`s. Are you bypassing the normal rendering process? You should never see `<br data-jekyll-commonmark-ghpages>` in your final output.

**Comment by lpugin** [comment]
I am not bypassing the normal rendering process. The `<br data-jekyll-commonmark-ghpages>` do appear in the output generated on the github server (see http://www.verovio.org/command-line.xhtml generated from https://github.com/rism-ch/verovio/blob/gh-pages/command-line.xhtml#L42-L44)

I tested the change submitted and it works. (But the `<br />` are still in the output)

**Comment by kivikakk** [comment]
Huh, I'm a bit lost. I looked at your repo, and your `_config.yml` has the following:

```yaml
markdown: kramdown
```

How is it you're using `jekyll-commonmark-ghpages`/testing changes to it? I'd like to set up a reproduction locally so I can try to debug why the `<br …>`s are appearing in output. We shouldn't be seeing them at all, basically.

**Comment by lpugin** [comment]
I tested locally by changing the config to `markdown: CommonMarkGhPages`, and then installing the plugin locally where I was able to test the modification. The output has `<br data-jekyll-commonmark-ghpages="true" />`in it.

Now of course I also do not understand why `CommonMarkGhPages` is used when the config says `kramdown`, but this is obviously something on the GitHub side which I cannot investigate.

**Comment by kivikakk** [comment]
I've found the source of the bug — this code is being executed even for non-CommonMark pages; a fix will be forthcoming.

**Comment by kivikakk** [comment]
Tested fix locally, verified working. I'll let you know when it's published to Pages live, then a rebuild will fix this.

**Comment by kivikakk** [comment]
This should now be fixed. If you push a new commit to restart the build, you should find the command-line.xhtml is rendering correctly 👍

**Comment by kivikakk** [comment]
(I've triggered a manual build from our side, and it's now looking good: http://www.verovio.org/command-line.xhtml)

**Comment by lpugin** [comment]
Great! Many thanks for taking care of this

**Pull request closed without merging**
